#in this file like
#Deployment
#ReplicaSet
#Pod
#Service all are there


apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  replicas: 1             # ur r defining here how many pods here
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata: 
   name: rabbitmq  # service name

spec:
  selector:
      project: roboshop
      component: rabbitmq          # this same selector will thtat pod labels also have
      tier: db
  ports:
     - protocol: TCP
       port: 5672 # sevice port
       targetPort: 5672 # container port   forwart req to another container
