apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongodb
   namespace: roboshop
   # these are replica set labels
   labels:
      project: roboshop
      component: mongodb
      tier: database

spec:
   replicas: 1
   # these labels are used to select pods
   selector: 
      matchLabels:
           project: roboshop
           component: mongodb
           tier: database
#like pod defination we are not giving pod name here
   template:
      metadata:
        labels:
           project: roboshop
           component: mongodb
           tier: database
      spec:
        containers:
        - name: mongodb
          image: kanakavignesh/mongodb:v1   
 
                  