#in this file like
#Deployment
#ReplicaSet
#Pod
#Service all are there


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1             # ur r defining here how many pods here
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: kanakavignesh/mongodb:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata: 
   name: mongodb  # service name

spec:
  selector:
      project: roboshop
      component: mongodb          # this same selector will thtat pod labels also have
      tier: db
  ports:
     - protocol: TCP
       port: 27017 # sevice port
       targetPort: 27017 # container port   forwart req to another container
