#in this file like
#Deployment
#ReplicaSet
#Pod
#Service all are there


apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: redis
    tier: db
spec:
  replicas: 1             # ur r defining here how many pods here
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: redis
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:7.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata: 
   name: redis  # service name
   namespace: roboshop

spec:
  selector:
      project: roboshop
      component: redis          # this same selector will thtat pod labels also have
      tier: db
  ports:
     - protocol: TCP
       port: 6379 # sevice port
       targetPort: 6379 # container port   forwart req to another container
